clc; clear all;
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\data\jlambert\Experiment\TMS_TFUS_Map\YB_TFUS_MAP_S1\TMS_S1.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/12/21 15:06:19

% Import the data
[~, ~, raw] = xlsread('D:\data\jlambert\Experiment\TMS_TFUS_Map\YB_TFUS_MAP_S1\TMS_YB_S1.xlsx','Sheet1','A2:L401');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,7,8,9,10]);
raw = raw(:,[2,3,4,5,6,11,12]);
% Create output variable
data = reshape([raw{:}],size(raw));
% Create table
TMS = table;
% Allocate imported array to column variable names
TMS.TMSresponse = cellVectors(:,1);
TMS.PeaktopeakV = data(:,1);
TMS.Latencypeak1 = data(:,2);
TMS.Latencypeak2 = data(:,3);
TMS.Peaktopeakduration = data(:,4);
TMS.Stimintensity = data(:,5);
TMS.TMSCoil = cellVectors(:,2);
TMS.Coilposition = cellVectors(:,3);
TMS.Coilorientationqxqyqzqw = cellVectors(:,4);
TMS.EMGchannel = cellVectors(:,5);
TMS.StimulusId = data(:,6);
TMS.TMSstimulustime = data(:,7);
% Clear temporary variables
clearvars data raw cellVectors;

% Parsing the CoilPosition column into 3 distinct field
for i=1:size(TMS.Coilposition,1)
    IndComma=find(TMS.Coilposition{i,:}==',');
    A=cell2mat(TMS.Coilposition(i,1));
    TMS.CoilPositionX(i) = str2num(A(1:IndComma(1)-1));
    TMS.CoilPositionY(i) = str2num(A(IndComma(1)+1:IndComma(2)-1));
    TMS.CoilPositionZ(i) = str2num(A(IndComma(2)+1:end));
end
%
for j=1:size(TMS.EMGchannel,1)
   if (TMS.EMGchannel{j,:}=='EMG1') 
   TMS_IndEMG1(j)=j;
   else
   IndEMG2(j)=j; 
   end
end
TMS_IndEMG1_ok = TMS_IndEMG1(TMS_IndEMG1~=0);
TMS_IndEMG2_ok = IndEMG2(IndEMG2~=0);

% New table containing only EMG channel 1 data
TMSEMG1 = table;
TMSEMG1.TMSresponse = TMS.TMSresponse(TMS_IndEMG1_ok);
TMSEMG1.PeaktopeakV = TMS.PeaktopeakV(TMS_IndEMG1_ok);
TMSEMG1.Latencypeak1 = TMS.Latencypeak1(TMS_IndEMG1_ok);
TMSEMG1.Latencypeak2 = TMS.Latencypeak2(TMS_IndEMG1_ok);
TMSEMG1.Peaktopeakduration = TMS.Peaktopeakduration(TMS_IndEMG1_ok);
TMSEMG1.Stimintensity = TMS.Stimintensity(TMS_IndEMG1_ok);
TMSEMG1.TMSCoil = TMS.TMSCoil(TMS_IndEMG1_ok);
TMSEMG1.Coilposition = TMS.Coilposition(TMS_IndEMG1_ok) ;
TMSEMG1.Coilorientationqxqyqzqw = TMS.Coilorientationqxqyqzqw(TMS_IndEMG1_ok);
TMSEMG1.EMGchannel = TMS.EMGchannel(TMS_IndEMG1_ok);
TMSEMG1.StimulusId = TMS.StimulusId(TMS_IndEMG1_ok);
TMSEMG1.TMSstimulustime = TMS.TMSstimulustime(TMS_IndEMG1_ok);
TMSEMG1.CoilPositionX = TMS.CoilPositionX(TMS_IndEMG1_ok);
TMSEMG1.CoilPositionY = TMS.CoilPositionY(TMS_IndEMG1_ok);
TMSEMG1.CoilPositionZ = TMS.CoilPositionZ(TMS_IndEMG1_ok);
% New table containing only EMG channel 2 data
TMSEMG2 = table;
TMSEMG2.TMSresponse = TMS.TMSresponse(TMS_IndEMG2_ok);
TMSEMG2.PeaktopeakV = TMS.PeaktopeakV(TMS_IndEMG2_ok);
TMSEMG2.Latencypeak1 = TMS.Latencypeak1(TMS_IndEMG2_ok);
TMSEMG2.Latencypeak2 = TMS.Latencypeak2(TMS_IndEMG2_ok);
TMSEMG2.Peaktopeakduration = TMS.Peaktopeakduration(TMS_IndEMG2_ok);
TMSEMG2.Stimintensity = TMS.Stimintensity(TMS_IndEMG2_ok);
TMSEMG2.TMSCoil = TMS.TMSCoil(TMS_IndEMG2_ok);
TMSEMG2.Coilposition = TMS.Coilposition(TMS_IndEMG2_ok) ;
TMSEMG2.Coilorientationqxqyqzqw = TMS.Coilorientationqxqyqzqw(TMS_IndEMG2_ok);
TMSEMG2.EMGchannel = TMS.EMGchannel(TMS_IndEMG2_ok);
TMSEMG2.StimulusId = TMS.StimulusId(TMS_IndEMG2_ok);
TMSEMG2.TMSstimulustime = TMS.TMSstimulustime(TMS_IndEMG2_ok);
TMSEMG2.CoilPositionX = TMS.CoilPositionX(TMS_IndEMG2_ok);
TMSEMG2.CoilPositionY = TMS.CoilPositionY(TMS_IndEMG2_ok);
TMSEMG2.CoilPositionZ = TMS.CoilPositionZ(TMS_IndEMG2_ok);
%% Params

NumberTrials = 200;
SubjName = 'YB';
SessionNum = 1;

%%
load('bl ep-select ep but 20171221_1010-emg1_TMS_Session1.mat');
time=linspace(-0.05,0.5,512);

for i = 1:NumberTrials
    EMG_TimeRange = find(time>=0.015&time<=0.05);
    TMSEMG1.PtPVal(i) = double(abs(max(data(i,1,:,:,:,EMG_TimeRange)))+abs(min(data(i,1,:,:,:,EMG_TimeRange))));
end

%%
TMS_PtPValuesEMG1 = unique(sort(TMSEMG1.PtPVal));
TMS_PtPValuesEMG2 = unique(sort(TMS.PeaktopeakV(TMS_IndEMG2_ok)));
TMS_R1 = linspace(0,1,length(TMS_PtPValuesEMG1))';
TMS_G1 = linspace(0,0,length(TMS_PtPValuesEMG1))';
TMS_B1 = linspace(1,0,length(TMS_PtPValuesEMG1))';
% Define Arbitrary Function for Plotting
TMS_HomeColor1 = [TMS_R1 TMS_G1 TMS_B1];
TMS_R2 = linspace(0,1,length(TMS_PtPValuesEMG2))';
TMS_G2 = linspace(0,0,length(TMS_PtPValuesEMG2))';
TMS_B2 = linspace(1,0,length(TMS_PtPValuesEMG2))';
% Define Arbitrary Function for Plotting
TMS_HomeColor2 = [TMS_R2 TMS_G2 TMS_B2];
%% Interpolation of the EMG amplitude according to a mesh interpolated based on the coordinates of stimulation
[X_Interpol,Y_Interpol]=meshgrid(linspace(min(TMSEMG1.CoilPositionX),max(TMSEMG1.CoilPositionX),500),linspace(min(TMSEMG1.CoilPositionY),max(TMSEMG1.CoilPositionY),500));%MA: meshgrid 2D
Z_TMSEMG1=griddata(TMSEMG1.CoilPositionX,TMSEMG1.CoilPositionY,TMSEMG1.PtPVal,X_Interpol,Y_Interpol,'linear');%MA: interpolate scattered data
figure;
%surf(X,Y,Z,'EdgeColor','none','LineStyle','none');%MA: 3D
imagesc(-linspace(min(TMSEMG1.CoilPositionX),max(TMSEMG1.CoilPositionX),100),linspace(min(TMSEMG1.CoilPositionY),max(TMSEMG1.CoilPositionY),100),Z_TMSEMG1);%MA: 3D
hold on;
for k = 1:size(TMSEMG1.PeaktopeakV,1)
    % Plot line with color selected by random number
    plot3(-TMSEMG1.CoilPositionX(k),TMSEMG1.CoilPositionY(k),TMSEMG1.PtPVal(k)+10,'o','Color',TMS_HomeColor1(find(TMSEMG1.PtPVal(k)==TMS_PtPValuesEMG1),:),'MarkerFaceColor',TMS_HomeColor1(find(TMSEMG1.PtPVal(k)==TMS_PtPValuesEMG1),:),'MarkerSize',10)
%     plot(TMSS1.CoilPositionX(IndEMG1_ok(k)),TMSS1.CoilPositionY(IndEMG1_ok(k)),'o')
    text(-TMSEMG1.CoilPositionX(k)+0.5,TMSEMG1.CoilPositionY(k)+0.5,num2str(k))
end
hold off;
title('Map TMS EMG Channel 1')

[X_Interpol,Y_Interpol]=meshgrid(linspace(min(TMSEMG1.CoilPositionX),max(TMSEMG1.CoilPositionX),500),linspace(min(TMSEMG1.CoilPositionY),max(TMSEMG1.CoilPositionY),500));%MA: meshgrid 2D
F = scatteredInterpolant(TMSEMG1.CoilPositionX,TMSEMG1.CoilPositionY,TMSEMG1.PtPVal);
TMSEMG1_Interpol = F(X_Interpol,Y_Interpol);
figure
mesh(X_Interpol,Y_Interpol,TMSEMG1_Interpol);
hold on;
plot3(TMSEMG1.CoilPositionX,TMSEMG1.CoilPositionY,TMSEMG1.PtPVal,'o');
hold off;

figure
surf(-X_Interpol,Y_Interpol,Z_TMSEMG1)

% Channel commented --> not interesting according to the scope of the
% experiment!
% [X_TMSEMG2,Y_TMSEMG2]=meshgrid(linspace(min(TMSEMG2.CoilPositionX),max(TMSEMG2.CoilPositionX),100),linspace(min(TMSEMG2.CoilPositionY),max(TMSEMG2.CoilPositionY),100));%MA: meshgrid 2D
% Z_TMSEMG2=griddata(TMSEMG2.CoilPositionX,TMSEMG2.CoilPositionY,TMSEMG2.PeaktopeakV,X_TMSEMG2,Y_TMSEMG2,'v4');%MA: interpolate scattered data
% figure;
% %surf(X,Y,Z,'EdgeColor','none','LineStyle','none');%MA: 3D
% imagesc(-linspace(min(TMSEMG2.CoilPositionX),max(TMSEMG2.CoilPositionX),100),linspace(min(TMSEMG2.CoilPositionY),max(TMSEMG2.CoilPositionY),100),Z_TMSEMG2);%MA: 3D
% hold on;
% for l = 1:size(TMSEMG2.PeaktopeakV,1)
%     % Arbitrary function which relies on the random variable
%     % Plot line with color selected by random number
%     plot3(-TMSEMG2.CoilPositionX(l),TMSEMG2.CoilPositionY(l),TMSEMG2.PeaktopeakV(l)+10,'o','Color',TMS_HomeColor1(find(TMSEMG2.PeaktopeakV(l)==TMS_PtPValuesEMG2),:),'MarkerFaceColor',TMS_HomeColor1(find(TMSEMG2.PeaktopeakV(l)==TMS_PtPValuesEMG2),:),'MarkerSize',10)
% %     plot(TMSS1.CoilPositionX(IndEMG1_ok(k)),TMSS1.CoilPositionY(IndEMG1_ok(k)),'o')
%     text(-TMSEMG2.CoilPositionX(l),TMSEMG2.CoilPositionY(l),num2str(l))
% end
% hold off;
% title('Map TMS EMG Channel 2')
%% Mapping of the sensation reported
Tmsexpe = load('DonneesTMSmapping_YB_Session1_TMS.mat', 'TMS');
Tmsexpe = struct2table(Tmsexpe.TMS);
TMSExpe = table;
TMSExpe.ISI = Tmsexpe.ISI';
TMSExpe.SubjectReport = Tmsexpe.SubjectReport';
for w = 1 : length(TMSExpe.SubjectReport)
    if strcmp(TMSExpe.SubjectReport(w),'')
        TMSExpe.Sensation(w)=0;
    else
        TMSExpe.Sensation(w)=1;
    end
end

Z_TMSsensation=griddata(TMSEMG1.CoilPositionX,TMSEMG1.CoilPositionY,TMSExpe.Sensation',X_Interpol,Y_Interpol,'cubic');%MA: interpolate scattered data
figure;
%surf(X,Y,Z,'EdgeColor','none','LineStyle','none');%MA: 3D
imagesc(-linspace(min(TMSEMG1.CoilPositionX),max(TMSEMG1.CoilPositionX),100),linspace(min(TMSEMG1.CoilPositionY),max(TMSEMG1.CoilPositionY),100),Z_TMSsensation);%MA: 3D
hold on;
for k = 1:size(TMSEMG1.PeaktopeakV,1)
    % Arbitrary function which relies on the random variable
    % Plot line with color selected by random number
    plot3(-TMSEMG1.CoilPositionX(k),TMSEMG1.CoilPositionY(k),TMSEMG1.PeaktopeakV(k)+10,'o','Color',TMS_HomeColor1(find(TMSEMG1.PtPVal(k)==TMS_PtPValuesEMG1),:),'MarkerFaceColor',TMS_HomeColor1(find(TMSEMG1.PtPVal(k)==TMS_PtPValuesEMG1),:),'MarkerSize',10)
%     plot(TMSS1.CoilPositionX(IndEMG1_ok(k)),TMSS1.CoilPositionY(IndEMG1_ok(k)),'o')
    text(-TMSEMG1.CoilPositionX(k)+0.5,TMSEMG1.CoilPositionY(k)+0.5,num2str(k))
end
hold off;
title('Map TMS EMG Channel 1 - Sensations')
%% Removing artifact / misplacement
TMSEMG1R=TMSEMG1;
TMSExpeR=TMSExpe;
TrialToReject = 35;
TMSEMG1R(TrialToReject,:)=[];
TMSExpeR(TrialToReject,:)=[];

% Interpolation of the EMG amplitude according to a mesh interpolated based on the coordinates of stimulation
[X_InterpolR,Y_InterpolR]=meshgrid(linspace(min(TMSEMG1R.CoilPositionX),max(TMSEMG1R.CoilPositionX),100),linspace(min(TMSEMG1R.CoilPositionY),max(TMSEMG1R.CoilPositionY),100));%MA: meshgrid 2D
Z_TMSEMG1R=griddata(TMSEMG1R.CoilPositionX,TMSEMG1R.CoilPositionY,TMSEMG1R.PtPVal,X_InterpolR,Y_InterpolR,'v4');%MA: interpolate scattered data
figure;
%surf(X,Y,Z,'EdgeColor','none','LineStyle','none');%MA: 3D
imagesc(-linspace(min(TMSEMG1R.CoilPositionX),max(TMSEMG1R.CoilPositionX),100),linspace(min(TMSEMG1R.CoilPositionY),max(TMSEMG1R.CoilPositionY),100),Z_TMSEMG1R);%MA: 3D
hold on;
for k = 1:size(TMSEMG1R.PeaktopeakV,1)
    % Arbitrary function which relies on the random variable
    % Plot line with color selected by random number
    plot3(-TMSEMG1R.CoilPositionX(k),TMSEMG1R.CoilPositionY(k),TMSEMG1R.PtPVal(k)+10,'o','Color',TMS_HomeColor1(find(TMSEMG1R.PtPVal(k)==TMS_PtPValuesEMG1),:),'MarkerFaceColor',TMS_HomeColor1(find(TMSEMG1R.PtPVal(k)==TMS_PtPValuesEMG1),:),'MarkerSize',10)
%     plot(TMSS1.CoilPositionX(IndEMG1_ok(k)),TMSS1.CoilPositionY(IndEMG1_ok(k)),'o')
    text(-TMSEMG1R.CoilPositionX(k)+0.5,TMSEMG1R.CoilPositionY(k)+0.5,num2str(k))
end
hold off;
title('Map TMS EMG Channel 1 - Artifact and misplacement removed')

Z_TMSsensationR=griddata(TMSEMG1R.CoilPositionX,TMSEMG1R.CoilPositionY,TMSExpeR.Sensation,X_Interpol,Y_Interpol,'cubic');%MA: interpolate scattered data
figure;
%surf(X,Y,Z,'EdgeColor','none','LineStyle','none');%MA: 3D
imagesc(-linspace(min(TMSEMG1R.CoilPositionX),max(TMSEMG1R.CoilPositionX),100),linspace(min(TMSEMG1R.CoilPositionY),max(TMSEMG1R.CoilPositionY),100),Z_TMSsensationR);%MA: 3D
hold on;
for k = 1:size(TMSEMG1R.PeaktopeakV,1)
    % Arbitrary function which relies on the random variable
    % Plot line with color selected by random number
    plot3(-TMSEMG1R.CoilPositionX(k),TMSEMG1R.CoilPositionY(k),TMSEMG1R.PtPVal(k)+10,'o','Color',TMS_HomeColor1(find(TMSEMG1R.PtPVal(k)==TMS_PtPValuesEMG1),:),'MarkerFaceColor',TMS_HomeColor1(find(TMSEMG1R.PtPVal(k)==TMS_PtPValuesEMG1),:),'MarkerSize',10)
%     plot(TMSS1.CoilPositionX(IndEMG1_ok(k)),TMSS1.CoilPositionY(IndEMG1_ok(k)),'o')
    text(-TMSEMG1R.CoilPositionX(k)+0.5,TMSEMG1R.CoilPositionY(k)+0.5,num2str(k))
end
hold off;
title('Map TMS Sensations - Artifact / misplacement removed')


NamefileTMS = ['Results_TMS_Mapping_' SubjName '_Session' num2str(SessionNum)];
save(NamefileTMS)

 
 %%

